# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/selection.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/selection.ipynb 4
from dash import Dash, dcc, html
from .manuscriptFiles import currentManuscripts

# %% ../nbs/selection.ipynb 6
def foo(): pass
