# AUTOGENERATED! DO NOT EDIT! File to edit: ../glyptodonApp.ipynb.

# %% auto 0
__all__ = []

# %% ../glyptodonApp.ipynb 3
import dash
from dash import html, dcc
import dash_bootstrap_components as dbc
from .navbar import create_navbar
