# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/glyptodonApp.ipynb.

# %% auto 0
__all__ = ['NAVBAR', 'FA621', 'APP_TITLE', 'app']

# %% ../nbs/glyptodonApp.ipynb 3
import dash
from dash import html, dcc
import dash_bootstrap_components as dbc

# %% ../nbs/glyptodonApp.ipynb 5
import navbar as nav

# %% ../nbs/glyptodonApp.ipynb 7
NAVBAR = nav.createNavbar()
FA621 = "https://use.fontawesome.com/releases/v6.2.1/css/all.css"
APP_TITLE = "Glyptodon"

# %% ../nbs/glyptodonApp.ipynb 9
app = dash.Dash(
    __name__,
    suppress_callback_exceptions=True,
    external_stylesheets=[
        dbc.themes.LUX,  # Dash Themes CSS
        FA621,  # Font Awesome Icons CSS
    ],
    title=APP_TITLE,
    use_pages=True,  # New in Dash 2.7 - Allows us to register pages
)
