# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/glyptodonApp.ipynb.

# %% auto 0
__all__ = ['NAVBAR', 'FA621', 'APP_TITLE']

# %% ../nbs/glyptodonApp.ipynb 3
import dash
from dash import html, dcc
import dash_bootstrap_components as dbc
from .navbar import createNavbar

# %% ../nbs/glyptodonApp.ipynb 5
NAVBAR = createNavbar()
FA621 = "https://use.fontawesome.com/releases/v6.2.1/css/all.css"
APP_TITLE = "Glyptodon"
