# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/navbar.ipynb.

# %% auto 0
__all__ = ['createNavbar']

# %% ../nbs/navbar.ipynb 4
from dash import html
import dash_bootstrap_components as dbc

# %% ../nbs/navbar.ipynb 10
def createNavbar():
    #    githubIcon = githubIcon()
    #    dropdownMenu = dropdownMenu()

    navbar = dbc.NavbarSimple(
        children=[
            dbc.NavItem(
                dbc.NavLink(
                    [html.I(className="fa-brands fa-github"), " "],
                    href="https://github.com/Accessible-Data-and-Code/glyptodon",
                    target="_blank",
                )
            ),
            dbc.DropdownMenu(
                nav=True,
                in_navbar=True,
                label="Menu",
                align_end=True,
                children=[
                    dbc.DropdownMenuItem("Home", href="/"),
                    dbc.DropdownMenuItem(divider=True),
                    dbc.DropdownMenuItem("1: Selection", href="/selection"),
                    dbc.DropdownMenuItem("2: Information", href="/information"),
                    dbc.DropdownMenuItem("3: Annotation", href="/annotation"),
                    dbc.DropdownMenuItem("4: Export", href="/export"),
                ],
            ),
        ],
        brand="Home",
        brand_href="/",
        # sticky="top",  # Uncomment if you want the navbar to always appear at the top on scroll.
        color="Primary",  # Change this to change color of the navbar e.g. "primary", "secondary" etc.
        dark=False,  # Change this to change color of text within the navbar (False for dark text)
    )

    return navbar
