# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_widgetCalls.ipynb.

# %% auto 0
__all__ = ['orangeButton', 'blueButton', 'tealButton']

# %% ../00_widgetCalls.ipynb 4
import ipywidgets as widgets

def orangeButton(text):
    return widgets.Button(description = text,
                          button_style = 'warning',
                          layout = widgets.Layout(height = '50px',
                                                  width = '200px'
                                                 )
                         )

def blueButton(text):
    return widgets.Button(description = text,
                          button_style = 'primary',
                          layout = widgets.Layout(height = '50px',
                                                  width = '200px'
                                                 )
                         )

def tealButton(text):
    return widgets.Button(description = text,
                          button_style = 'info',
                          layout = widgets.Layout(height = '50px',
                                                  width = '200px'
                                                 )
                         )
