# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_widgetCalls.ipynb.

# %% auto 0
__all__ = ['orangeButton', 'blueButton', 'tealButton', 'textWidge']

# %% ../00_widgetCalls.ipynb 4
import ipywidgets as widgets

def orangeButton(text):
    return widgets.Button(description = text,
                          button_style = 'warning',
                          layout = widgets.Layout(height = '50px',
                                                  width = '200px'
                                                 )
                         )

def blueButton(text):
    return widgets.Button(description = text,
                          button_style = 'primary',
                          layout = widgets.Layout(height = '50px',
                                                  width = '200px'
                                                 )
                         )

def tealButton(text):
    return widgets.Button(description = text,
                          button_style = 'info',
                          layout = widgets.Layout(height = '50px',
                                                  width = '200px'
                                                 )
                         )

# %% ../00_widgetCalls.ipynb 7
import ipywidgets as widgets

def textWidge(info):
    return widgets.Text(description =info,
                        placeholder = info,
                        layout = widgets.Layout(height = 'auto',
                                                width = 'auto',
                                                align_items = 'center'
                                               )
                       )
